-- Restaura o cadastro real de TAP usado pelo Cockpit e remove cadastros locais/fictícios
-- que não representam uma TAP válida no Supabase.

delete from public.projects
where code in ('default', 'PRJ-ROSSI SUPERMERCADOS')
   or name in ('Projeto Padrão', 'PRJ-ROSSI SUPERMERCADOS')
   or (code = 'SUPERMERCADO_ROSSI_NEW_LTDA' and id <> '426088ef-b39e-4711-8925-48da1062ec1a');

insert into public.projects (id, code, name, client_name, manager_totvs, manager_client, status)
values (
  '426088ef-b39e-4711-8925-48da1062ec1a',
  'SUPERMERCADO_ROSSI_NEW_LTDA',
  'SUPERMERCADO ROSSI NEW LTDA',
  'SUPERMERCADO ROSSI NEW LTDA',
  'Regis Reis',
  'Claudinete Vieira',
  'ativo'
)
on conflict (id) do update set
  code = excluded.code,
  name = excluded.name,
  client_name = excluded.client_name,
  manager_totvs = excluded.manager_totvs,
  manager_client = excluded.manager_client,
  status = excluded.status,
  updated_at = now();

insert into public.tap_entries (
  id,
  project_id,
  identificacao,
  data_referencia,
  tap_payload_id,
  data_tap,
  cod_cliente,
  nome_projeto,
  gpp,
  coordenador,
  coordenador_projeto,
  esn,
  arquiteto,
  criticidade_cliente,
  criticidade_totvs,
  drive,
  produtos,
  produto,
  detalhes_produtos,
  valor_projeto,
  receita_atual,
  margem_venda,
  margem_venda_percentual,
  margem_atual,
  margem_atual_percentual,
  margem_venda_valor,
  margem_atual_valor,
  mrr_mensal,
  mrr_recorrente_mensal,
  investimento_perdas,
  mrr_total,
  mrr_total_contratados,
  investimento_comercial,
  psa_planejado,
  investimento_erro,
  investimento_erro_produto,
  diferenca_psa,
  diferenca_psa_projeto,
  projeto_em_perda,
  data_inicio,
  go_live,
  go_live_previsao,
  duracao,
  pos_producao,
  pos_producao_meses,
  encerramento,
  observacao,
  observacoes,
  payload,
  updated_at
)
values (
  '02402d45-4c62-4216-bdaa-82f98ddaea0a',
  '426088ef-b39e-4711-8925-48da1062ec1a',
  '02402d45-4c62-4216-bdaa-82f98ddaea0a',
  '2026-05-10',
  '02402d45-4c62-4216-bdaa-82f98ddaea0a',
  '2026-05-10',
  '["TDC0CC", "TDC02R"]'::jsonb,
  'SUPERMERCADO ROSSI NEW LTDA',
  'Fábio Daumichen',
  'Regis Reis',
  'Regis Reis',
  'Daniel Abdalla',
  null,
  'MÉDIA',
  'MÉDIA',
  null,
  '[]'::jsonb,
  null,
  '{}'::jsonb,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  'Não',
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  'TAP restaurada a partir do cadastro validado do projeto SUPERMERCADO ROSSI NEW LTDA.',
  'TAP restaurada a partir do cadastro validado do projeto SUPERMERCADO ROSSI NEW LTDA.',
  jsonb_build_object(
    'id', '02402d45-4c62-4216-bdaa-82f98ddaea0a',
    'dataTap', '2026-05-10',
    'codCliente', jsonb_build_array('TDC0CC', 'TDC02R'),
    'nomeProjeto', 'SUPERMERCADO ROSSI NEW LTDA',
    'gpp', 'Fábio Daumichen',
    'coordenador', 'Regis Reis',
    'esn', 'Daniel Abdalla',
    'arquiteto', '',
    'criticidadeCliente', 'MÉDIA',
    'criticidadeTotvs', 'MÉDIA',
    'drive', '',
    'produtos', '[]'::jsonb,
    'detalhesProdutos', '{}'::jsonb,
    'valorProjeto', '',
    'receitaAtual', '',
    'margemVenda', '',
    'margemAtual', '',
    'margemVendaValor', '',
    'margemAtualValor', '',
    'mrrMensal', '',
    'investimentoPerdas', '',
    'mrrTotal', '',
    'investimentoComercial', '',
    'psaPlanejado', '',
    'investimentoErro', '',
    'diferencaPsa', '',
    'projetoEmPerda', 'Não',
    'dataInicio', '',
    'goLive', '',
    'duracao', '',
    'posProducao', '',
    'encerramento', '',
    'observacao', 'TAP restaurada a partir do cadastro validado do projeto SUPERMERCADO ROSSI NEW LTDA.'
  ),
  now()
)
on conflict (id) do update set
  project_id = excluded.project_id,
  identificacao = excluded.identificacao,
  data_referencia = excluded.data_referencia,
  tap_payload_id = excluded.tap_payload_id,
  data_tap = excluded.data_tap,
  cod_cliente = excluded.cod_cliente,
  nome_projeto = excluded.nome_projeto,
  gpp = excluded.gpp,
  coordenador = excluded.coordenador,
  coordenador_projeto = excluded.coordenador_projeto,
  esn = excluded.esn,
  arquiteto = excluded.arquiteto,
  criticidade_cliente = excluded.criticidade_cliente,
  criticidade_totvs = excluded.criticidade_totvs,
  drive = excluded.drive,
  produtos = excluded.produtos,
  produto = excluded.produto,
  detalhes_produtos = excluded.detalhes_produtos,
  valor_projeto = excluded.valor_projeto,
  receita_atual = excluded.receita_atual,
  margem_venda = excluded.margem_venda,
  margem_venda_percentual = excluded.margem_venda_percentual,
  margem_atual = excluded.margem_atual,
  margem_atual_percentual = excluded.margem_atual_percentual,
  margem_venda_valor = excluded.margem_venda_valor,
  margem_atual_valor = excluded.margem_atual_valor,
  mrr_mensal = excluded.mrr_mensal,
  mrr_recorrente_mensal = excluded.mrr_recorrente_mensal,
  investimento_perdas = excluded.investimento_perdas,
  mrr_total = excluded.mrr_total,
  mrr_total_contratados = excluded.mrr_total_contratados,
  investimento_comercial = excluded.investimento_comercial,
  psa_planejado = excluded.psa_planejado,
  investimento_erro = excluded.investimento_erro,
  investimento_erro_produto = excluded.investimento_erro_produto,
  diferenca_psa = excluded.diferenca_psa,
  diferenca_psa_projeto = excluded.diferenca_psa_projeto,
  projeto_em_perda = excluded.projeto_em_perda,
  data_inicio = excluded.data_inicio,
  go_live = excluded.go_live,
  go_live_previsao = excluded.go_live_previsao,
  duracao = excluded.duracao,
  pos_producao = excluded.pos_producao,
  pos_producao_meses = excluded.pos_producao_meses,
  encerramento = excluded.encerramento,
  observacao = excluded.observacao,
  observacoes = excluded.observacoes,
  payload = excluded.payload,
  updated_at = now();
